Status
code, "Url", "Label"
200, "https://ado-shop.com/?srsltid=AfmBOoopilrRJ5koNP1BzDm-Xu0M2YaEDi-MJzXVnOwjYo1cx8ZbSROj#MainContent", "Skip to content"
200, "https://ado-shop.com/collections/vivarium", "Vivarium"
200, "https://ado-shop.com/", "Home"
200, "https://ado-shop.com/collections/all", "ALL MUSIC"
200, "https://ado-shop.com/collections/all-merch", "ALL MERCH"
200, "https://ado-shop.com/collections/shinzou", "Shinzou"
200, "https://ado-shop.com/collections/hibana", "Hibana"
200, "https://ado-shop.com/collections/ados-best-adobum", "Ado's Best Adobum"
200, "https://ado-shop.com/collections/phantom-siita", "Phantom Siita"
200, "https://ado-shop.com/collections/horror-queen", "Phantom Siita - Horr"
